Changed Pictures and added Puzzle Trainers
acend/website-hugo pull request #77
Opened 2021-03-15 19:27 UTC by philogros

2021-03-15 19:28 UTC, phil-pona submitted a review, later dismissed

2021-03-15 20:29 UTC, bliemli requested changes

2021-03-15 20:29 UTC, bliemli commented on site/content/de/trainings/prometheus.md
> +      abstract : "Nicht einmal PromQL, in ihrer komplexesten Form, lassen ihn aus seiner Ruhe bringen. Mit seinem Knowhow verblüfft er regelmässig."
```suggestion
      abstract : "Nicht einmal PromQL, in ihrer komplexesten Form, lassen ihn aus seiner Ruhe bringen. Mit seinem Know-how verblüfft er regelmässig."
```

2021-03-16 07:22 UTC, phil-pona approved these changes

2021-03-16 07:43 UTC, bliemli approved these changes

2021-03-16 07:43 UTC, merged